<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>83ec922e-c4e9-4454-90ee-4403ac0236b3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_menu_toggle</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'menu-toggle')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>menu-toggle</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
</WebElementEntity>