<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b3e1a3a8-07cc-4561-92c4-a5ebd87d2100</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_go_to_homepage</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[7]/p[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Go to Homepage')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Go to Homepage</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
</WebElementEntity>