<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>92a75f2e-e7c4-4612-ac20-531c22e3562c</elementGuidId>
    <imagePath></imagePath>
    <name>button_btn_book_appointment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/form[1]/div[6]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'btn-book-appointment') and equals(@type,'submit') and equals(@text,'Book Appointment')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>btn-book-appointment</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Book Appointment</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
</WebElementEntity>