<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0a168159-93f3-4257-8a3f-c18f1da98118</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_btn_make_appointment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'btn-make-appointment') and equals(@text,'Make Appointment')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>btn-make-appointment</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Make Appointment</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
</WebElementEntity>