<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b4d1b5d-2060-4c51-90be-fdd7be96c062</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_history</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'History')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>History</value>
        <webElementGuid>92034139-b5ef-4263-ab63-69b6a50125d2</webElementGuid>
    </webElementProperties>
</WebElementEntity>