<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d453614d-ac1e-4052-88f8-67e343c09aac</elementGuidId>
    <imagePath></imagePath>
    <name>input_programs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/form[1]/div[3]/div[1]/label[2]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'programs') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>programs</value>
        <webElementGuid>92034139-b5ef-4263-ab63-69b6a50125d2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>92034139-b5ef-4263-ab63-69b6a50125d2</webElementGuid>
    </webElementProperties>
</WebElementEntity>