<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e14a232c-9b85-47f3-9950-3f6c1d67f39a</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_comment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/form[1]/div[5]/div[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'txt_comment') and equals(@name,'comment')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>txt_comment</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>comment</value>
        <webElementGuid>25336146-3504-42b2-b4cf-0bfa3c24fdb6</webElementGuid>
    </webElementProperties>
</WebElementEntity>